/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorychallengeappv1.framesMCA;

import java.awt.Color;
import java.awt.Font;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JToolTip;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import memorychallengeappv1.connections.ConnectionManager;

/**
 *
 * @author ser
 */
public class FrameBloqueInactivo extends javax.swing.JFrame {

    
    /**
     * Creates new form FrameBloqueInactivo
     */
    public FrameBloqueInactivo() {
        initComponents();
        bloquesInactivosVista();
        setLocationRelativeTo(null);
        setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelEjemplo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(77, 133, 133));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(219, 234, 233));
        jLabel1.setText("Bloques Inactivos");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });

        jPanelEjemplo.setBackground(new java.awt.Color(220, 219, 219));
        jPanelEjemplo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 219, 219)));

        javax.swing.GroupLayout jPanelEjemploLayout = new javax.swing.GroupLayout(jPanelEjemplo);
        jPanelEjemplo.setLayout(jPanelEjemploLayout);
        jPanelEjemploLayout.setHorizontalGroup(
            jPanelEjemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanelEjemploLayout.setVerticalGroup(
            jPanelEjemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelEjemplo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(243, 243, 243))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private ActionListener jbAbrirActionPerformed(int idBloque) 
        {                                             
            ActionListener al = new ActionListener() 
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                    FrameInfoBloqueInactivo fibi = new FrameInfoBloqueInactivo(idBloque);
                    fibi.setVisible(true);
                 //   throw new UnsupportedOperationException("Not supported yet."); 
                    
                }
            };
            return al;
        }  
        
        private ActionListener jbActivarActionPerformed(int idBloque) 
        {                                             
            ActionListener al = new ActionListener() 
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                   FrameEleccionTipoBloque fetb = new FrameEleccionTipoBloque(idBloque);
                   fetb.setVisible(true);
                    
                }
            };
            return al;
        }   

    
    
    
    boolean prendido = true;
    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved

        if(prendido)
        {
             jLabel1.setOpaque(true);
             jLabel1.setBackground(Color.WHITE);
             prendido = false;
             
        }
        else
        {  
             jLabel1.setOpaque(true);
             jLabel1.setBackground(new java.awt.Color(77,133,133));
             prendido = true;
        }
       
    }//GEN-LAST:event_jLabel1MouseMoved
    
    
    
    
  //  List <JLabel> nombres = new ArrayList<JLabel>();
    public void bloquesInactivosVista()
    {
   
        
        int count = 0;
        try 
           {
               Connection conn = ConnectionManager.getConnection();
               PreparedStatement stmt = conn.prepareStatement
                (
                 "SELECT ID_BLOQUE, nombre FROM db_memorychallengeapp.table_bloque b"
               + " INNER JOIN db_memorychallengeapp.table_bloqueinactivocorto bic on b.ID_BLOQUE = bic.ID_BLOQUE_IC"     
                 );
                ResultSet rs = stmt.executeQuery();
                int y = 40;

                while(rs.next())
                {  
                   int idBloque = rs.getInt("ID_BLOQUE");
                   String nombre = rs.getString("nombre");
                   String datosBloque = nombre ;
//                   for(int x = 0; x <5; x++)
//                   {
                        JButton jb = new JButton();
                        jb.setFont(new Font("Arial", Font.BOLD, 11));
                        jb.setText("Activar"); 
                        jb.setBounds(10, y, 70, 20);
                        jb.setVisible(true);
                        jb.addActionListener(jbActivarActionPerformed(idBloque));
                        jb.setBackground(Color.WHITE);
                        Border border2 = new LineBorder((Color.WHITE), 1, true);
                        jb.setBorder(border2);
                        jPanelEjemplo.add(jb);
                        
                        
                        JButton nombreBloque = new JButton(datosBloque) 
                        {
                          public JToolTip createToolTip()
                            {
                                JToolTip tip = super.createToolTip();
                                tip.setOpaque(true);
                             //   UIManager.put("tip.background", Color.white);
                                tip.setBackground(Color.WHITE);
                                tip.setForeground(new java.awt.Color(84, 192,115));
                                Border border = new LineBorder(new java.awt.Color(238,242,239), 2, true);
                                tip.setBorder(border);
                                return tip;
                            }
                        };
                        nombreBloque.setBounds(90, y, 410, 20);
                        nombreBloque.setVisible(true);
                        nombreBloque.setOpaque(true);
                        nombreBloque.setBackground(new java.awt.Color(9, 154, 213));
                        Border border = new LineBorder(new java.awt.Color(11,154,213), 2, true);
                        nombreBloque.setBorder(border);
                        nombreBloque.setForeground(Color.WHITE);
                        nombreBloque.setFont(new Font("Times New Roman", Font.BOLD, 13));
                        nombreBloque.setToolTipText("Da click para ver sus enunciados");
                        nombreBloque.addActionListener(jbAbrirActionPerformed(idBloque));
                        y = y+40;
                      //  nombres.add(nombreBloque);
                        jPanelEjemplo.add(nombreBloque);

                //    }
                        count =count+1;
                }
                int yPanel =764;
          //    count = count* 5;
                if((count)<=17)
                {
                   // jPanelEjemplo.setPreferredSize(new Dimension(594,764));
                    System.out.println("conteo: "+count);
                    yPanel =764;
                }
                else
                {
                    int diferencia = count-17;
                    for(int i = 0;i<diferencia;i++)
                    {
                        yPanel = yPanel+40;
                       // System.out.println(diferencia+" mucho");
                    }
                }
                jPanelEjemplo.setPreferredSize(new Dimension(594,yPanel));
                
                
           } 
        catch (SQLException e) 
           {
            //   Logger.getLogger(FrameBloqueInactivo.class.getName()).log(Level.SEVERE, null, ex);
                ConnectionManager.processException(e);
           }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBloqueInactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBloqueInactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBloqueInactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBloqueInactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBloqueInactivo().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEjemplo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
