/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorychallengeappv1.framesMCA;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
//import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import memorychallengeappv1.GestionEjecucionBloqueLargo;
import memorychallengeappv1.connections.ConnectionManager;

/**
 *
 * @author ser
 */
public class FrameConfigBloqueLargo extends javax.swing.JFrame {

    private int id_bloque;
    private int diasTotales = 0;
    /**
     * Creates new form FrameConfigBloqueLargo
     */
    public FrameConfigBloqueLargo(int id_bloqueL) {
        this.id_bloque = id_bloqueL;
        initComponents();
        itemsComboBox();
        aceptarOption();
         setLocationRelativeTo(null);
         
    }
    
    
   private void itemsComboBox()
   {
        String[] items = {"          Elige una duración ","Por tres días", "Por una semana", "Por dos semanas", "por un mes"};
       jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(items));
       jButtonAceptar.setVisible(false);
   }
   
   
           private ActionListener comboSelectActionPerformed() 
        {                                             
            ActionListener al = new ActionListener() 
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                    if (
                        jComboBox.getSelectedItem()=="Por tres días"
                        || jComboBox.getSelectedItem() == "Por una semana"
                        || jComboBox.getSelectedItem() =="Por dos semanas"
                        ||  jComboBox.getSelectedItem() =="por un mes"
                        )
                    {
                         jButtonAceptar.setVisible(true);
                    }
                    else
                    {
                        System.out.println("not item selected");
                        jButtonAceptar.setVisible(false);
                    }
                    
                 
                }
            };
            return al;
        }  
           
      private void aceptarOption()
    {
        
         jComboBox.addActionListener(comboSelectActionPerformed());

     }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(0, 153, 153));
        jPanelTitulo.setForeground(new java.awt.Color(0, 204, 255));

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("¿Por cuánto tiempo quieres que se repita el bloque?");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(38, 38, 38))
        );

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jButtonAceptar.setBackground(new java.awt.Color(9, 154, 213));
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(109, 109, 109))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        
        getConnection(id_bloque);
        GestionEjecucionBloqueLargo gebl = new GestionEjecucionBloqueLargo(id_bloque);
        dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        itemSelected();
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private int itemSelected()
    {
        if(this.jComboBox.getSelectedItem().equals("Por tres días"))
          {
              diasTotales = 3;

          }
          else if(this.jComboBox.getSelectedItem().equals("Por una semana"))
          {
              diasTotales = 7;

          }
          else if(this.jComboBox.getSelectedItem().equals("Por dos semanas"))
          {
              diasTotales = 15;

          }
          else if(this.jComboBox.getSelectedItem().equals("por un mes"))
          {
              diasTotales = 30;

          }
          else
          {
              
          }
          return diasTotales;
    
    }
    
        private void getConnection(int idBloque)
    { 

        
        System.out.println(id_bloque);
        
            try {
                Connection conn = ConnectionManager.getConnection();
               // conn.setAutoCommit(false);
                String query = 
                       "INSERT INTO db_memorychallengeapp.table_bloqueactivolargo"
                       + " (ID_BLOQUE_AL, fecha_agregacion, fecha_sig_rep, dias_totales, fecha_finalizacion)"
                       + " VALUES (?,now(),DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 min),1,?,null)";
                       
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setInt(1, id_bloque);
//                String dias = ((Integer)diasTotales).toString();
//                stmt.setString(2, dias);
                stmt.setInt(2, diasTotales);
//              
                int updt = stmt.executeUpdate();

//                if()
//                {
//                   
//                }
//
//
//                conn.commit();
                stmt.close();
            
                } catch (SQLException e) 
                {
                 ConnectionManager.processException(e);
                }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConfigBloqueLargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConfigBloqueLargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConfigBloqueLargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConfigBloqueLargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
         //       new FrameConfigBloqueLargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
